### ISSUE TITLE
Insufficient Subnets even when `gaol_linux list` reports fewer than `max_containers`

### ISSUE THREAD

**Issue by cjcjameson** [cloudfoundry/garden-runc-release#18]
## Todos

Please try the following before submitting the issue:

- [X] Upgrade Concourse if you are observing a failure in a test
- [X] Use latest BOSH stemcell if the problem occurred in a BOSH VM
- [n/a] Use Go 1.6 if the issue has to do with running unit tests locally

## Description

Running Concourse jobs were reporting "insufficient subnets remaining in the pool". We were unable to match this error message with a spike in container counts as reported by `fly workers`. It generally came up when load was high on the system, but it wasn't strictly correlated with metrics like CPU load either.

We went onto the worker VM, and ran `gaol_linux list`. It reported the same # of containers as `fly workers` was reporting. We looked at the `iptables -S` on the worker, and saw many more rules than active containers. In fact, we saw almost exactly 250. Logs attached.

We do not set the following parameters in our manifest, so we expect that the defaults were still:
- max_containers: 250 
- network_pool: 10.254.0.0/22 

`bosh recreate worker` worked to reset the iptables, and then we had a TSA registration issue (probably not a garden problem) and `bosh restart web` fixed that.

Is `bosh recreate worker` necessary any time one upgrades the runC version? For indeed, the runC behavior when it goes down should be to try to keep the containers around. But if it comes back up with new version of the software running, does it leave the existing iptables around?

#### Background on our particular situation:

We had been running Concourse 1.6 with runC 0.4.0 for a long time. We were running it hard, such that the error message "insufficient subnets remaining in the pool" usually signified hitting the container limit of 250 (actually). We bumped from 1.6 + 0.4.0 straight to Concourse 2.2.1 with runC 0.8.0

## Logging and/or test output

The `iptables -S` on a worker VM when it wasn't working (reporting many more rules than containers were supposedly running)

[worker-0-iptables.txt](https://github.com/cloudfoundry/garden-runc-release/files/517080/worker-0-iptables.txt)

Logs from the garden job (tgz as provided by `bosh logs`)

https://drive.google.com/file/d/0B2izPb3rj-6AeHZzejhaaXZvMFk/view?usp=sharing

## Steps to reproduce

Pretty elaborate; we didn't get a simple reproduction.

- Bosh deploy Concourse 1.6 + runC 0.4.0
- Run it hard, hit the container limit, observe "insufficient subnets remaining in the pool"
- Upgrade to Concourse 2.2.1 with runC 0.8.0
- Run it hard, observe "insufficient subnets remaining in the pool" occur when `fly workers` reports a number of containers less than 250

**Comment by garden-gnome** [comment]
Hi there!

We use Pivotal Tracker to provide visibility into what our team is working on. A story for this issue has been automatically created.

The current status is as follows:

* [ ] [#131921595](https://www.pivotaltracker.com/story/show/131921595) Insufficient Subnets even when `gaol_linux list` reports fewer than `max_containers`


This comment, as well as the labels on the issue, will be automatically updated as the status in Tracker changes.

**Comment by julz** [comment]
Going to close this as a dupe of https://github.com/cloudfoundry/guardian/issues/53 since it seems likely to be the same problem. Do please re-open if you disagree.
