### ISSUE TITLE
Support for checkpoint/restore in Garden?

### ISSUE THREAD

**Issue by abh1kg** [cloudfoundry/garden-runc-release#40]
## Todos

Please try the following before submitting the issue:

- [ ] Upgrade Concourse if you are observing a failure in a test
- [ ] Use latest BOSH stemcell if the problem occurred in a BOSH VM
- [ ] Use Go 1.6 if the issue has to do with running unit tests locally

## Description

I was unable to find this anywhere but is CRIU (Checkpoint/Restore in User-space) supported inside Garden? If not, is there a mechanism to live migrate a container (or parts of a container like active TCP connections)?

**Comment by julz** [comment]
Hi @abh1kg - it isn't currently as none of our main consumers has so far needed/requested the feature. Having said that the `runc` tool we use to actually run containers supports it so it probably isn't incredibly difficult for us to support (and we'd accept / help anyone who wanted to try to contribute a PR along those lines).
